version: '2'
services:
    results: #AI 결과를 저장할 Database
        image: mysql:5.7
        container_name: results
        ports: # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
        - "3307:3306" 
        environment: # -e 옵션
        - MYSQL_DATABASE=results
        - MYSQL_ROOT_PASSWORD=mysql  # MYSQL 패스워드 설정 옵션
        - TZ=Asia/Seoul
        command: # 명령어 실행
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        volumes: #현재위치
            - $PWD/results:/var/lib/mysql
    users: #서비스 사용자 정보 DB
        image: mysql:5.7
        container_name: users
        ports: # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
        - "3308:3306" 
        environment: # -e 옵션
        - MYSQL_DATABASE=result
        - MYSQL_ROOT_PASSWORD=mysql  # MYSQL 패스워드 설정 옵션
        - TZ=Asia/Seoul
        command: # 명령어 실행
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        volumes: #현재위치
            - $PWD/users:/var/lib/mysql
    arns: #S3에 저장된 객체의 ARN을 저장할 DB
        image: mysql:5.7
        container_name: arns
        ports: # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)  <- 컨테이너 내부는 무조건 3306
        - "3309:3306" 
        environment: # -e 옵션
        - MYSQL_DATABASE=arns
        - MYSQL_ROOT_PASSWORD=mysql  # MYSQL 패스워드 설정 옵션
        - TZ=Asia/Seoul
        command: # 명령어 실행
        - --character-set-server=utf8mb4
        - --collation-server=utf8mb4_unicode_ci
        volumes: #현재위치
            - $PWD/arns:/var/lib/mysql